spring.application.name=multiple-LLM

server.port=8080
#openrouter.api.key=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
spring.web.resources.static-locations=classpath:/static/

openrouter.api.key=${OPEN_API_KEY}
